# 构建配置
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Dockerfile
  - docker-compose.yml
  - README.md
  - assets/main.scss
  - assets/css/just-the-docs-dark.scss
  - assets/css/just-the-docs-light.scss
  - assets/css/just-the-docs.scss
  - _sass

